import { getPostData, getSortedPostsData } from '@/lib/posts';
import { notFound } from 'next/navigation';
import ReactMarkdown from 'react-markdown';
import remarkGfm from 'remark-gfm';
import AdBanner from '@/components/AdBanner';
import AmazonBanner from '@/components/AmazonBanner';

export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }) {
  const slug = (await params).slug;
  const post = getPostData(slug, 'blog');
  
  if (!post) return {};

  return {
    title: post.title,
    description: post.summary || post.title,
    openGraph: {
      title: post.title,
      description: post.summary || post.title,
      type: 'article',
      publishedTime: post.date,
    },
  };
}

export async function generateStaticParams() {
  const posts = getSortedPostsData('blog');
  return posts.map((post) => ({
    slug: post.slug,
  }));
}

export default async function BlogPostPage({ params }: { params: Promise<{ slug: string }> }) {
  const slug = (await params).slug;
  const post = getPostData(slug, 'blog');

  if (!post) {
    notFound();
  }

  return (
    <article className="max-w-3xl mx-auto px-4 py-12">
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{
          __html: JSON.stringify([
            {
              "@context": "https://schema.org",
              "@type": "BlogPosting",
              "headline": post.title,
              "datePublished": post.date,
              "description": post.summary || post.title,
              "author": {
                "@type": "Organization",
                "name": "NNHub"
              },
              "publisher": {
                "@type": "Organization",
                "name": "NNHub",
                "logo": {
                  "@type": "ImageObject",
                  "url": "https://newport-news-local.com/og-image.png"
                }
              }
            },
            {
              "@context": "https://schema.org",
              "@type": "BreadcrumbList",
              "itemListElement": [
                {
                  "@type": "ListItem",
                  "position": 1,
                  "name": "Home",
                  "item": "https://newport-news-local.com"
                },
                {
                  "@type": "ListItem",
                  "position": 2,
                  "name": "Blog",
                  "item": "https://newport-news-local.com/blog"
                },
                {
                  "@type": "ListItem",
                  "position": 3,
                  "name": post.title,
                  "item": `https://newport-news-local.com/blog/${slug}`
                }
              ]
            }
          ])
        }}
      />
      <header className="mb-10 text-center">
        <h1 className="text-4xl sm:text-5xl font-extrabold text-blue-900 tracking-tight mb-4">{post.title}</h1>
        <div className="flex flex-col items-center gap-2 text-slate-500 text-sm">
          <div className="flex items-center gap-4">
            <time>Last Updated: {post.date}</time>
            {post.category && (
               <span className="bg-yellow-100 text-yellow-800 px-2 py-1 rounded-full text-xs font-semibold">
                 {post.category}
               </span>
            )}
          </div>
        </div>
      </header>
      
      <div className="prose prose-lg prose-blue max-w-none mb-12">
        <ReactMarkdown remarkPlugins={[remarkGfm]}>
          {post.content}
        </ReactMarkdown>
      </div>

      <AdBanner dataAdSlot="blog_post_bottom" />
      <div className="mt-4">
        <AmazonBanner />
      </div>

      <hr className="border-slate-200 mb-8" />

      <footer className="bg-slate-50 rounded-xl p-6 border border-slate-100 italic text-slate-600 text-sm">
        <p className="mb-4">
          This article was generated by AI based on public data from <strong>Newport News Open Data</strong> and other official sources. 
          Please verify critical information via the original source links.
        </p>
        
        {post.link && (
          <div className="mt-4 not-italic">
            <a 
              href={post.link} 
              target="_blank" 
              rel="noopener noreferrer"
              className="inline-flex items-center gap-2 bg-blue-600 text-white px-4 py-2 rounded-lg hover:bg-blue-700 transition-colors font-medium text-sm"
            >
              🌐 View Official Source
            </a>
          </div>
        )}
      </footer>
    </article>
  );
}
